#!/usr/bin/env bash

CONFIGURED_PORT=$(snapctl get port)
CONFIGURED_FLAGS=$(snapctl get flags)

$SNAP/usr/sbin/tailscaled --cleanup

$SNAP/usr/sbin/tailscaled \
    --state=$SNAP_DATA/tailscaled.state \
    --socket=/run/snap.tailscale/tailscaled.sock \
    --port ${CONFIGURED_PORT:-41641} \
    $CONFIGURED_FLAGS
