name: tailscale
version: "1.10.2"
license: BSD-3-Clause
summary: The easiest, most secure way to use WireGuard and 2FA.
description: >
  Zero config VPN. Installs on any device in minutes, manages firewall rules for you, and works from anywhere.
icon: tailscale.png

base: core20
grade: devel
confinement: strict
compression: lzo

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: arm64
  # TODO: other archs

layout:
  /var/lib/tailscale:
    bind: $SNAP_DATA/var/lib/tailscale

plugs:
  hostfs-etc-resolv-conf:
    interface: system-files
    read:
      - /etc/resolv.conf
    write:
      - /etc/resolv.conf

apps:
  tailscale:
    command: usr/bin/tailscale --socket /run/snap.tailscale/tailscaled.sock

  service:
    command: usr/sbin/tailscale_snap_daemon
    daemon: simple
    post-stop-command: usr/sbin/tailscaled --cleanup
    restart-condition: on-failure
    plugs:
      - firewall-control
      - network
      - network-bind
      - network-control
      - system-backup
      - system-observe

parts:
  tailscale:
    plugin: dump
    # FIXME: SNAPCRAFT_TARGET_ARCH doesn't exactly match with tailscale's arch strings
    source: https://pkgs.tailscale.com/stable/tailscale_${SNAPCRAFT_PROJECT_VERSION}_${SNAPCRAFT_TARGET_ARCH}.tgz
    filesets:
      no-systemd:
        - -systemd
    organize:
      tailscale: usr/bin/
      tailscaled: usr/sbin/
    stage:
      - $no-systemd
    stage-packages:
      - iproute2
      - libatm1
      - systemctl

  scripts:
    plugin: dump
    source: snap/local
    organize:
      tailscale_snap_daemon: usr/sbin/
